use_frameworks!

platform :ios, '10.0'

target 'USMusicPlayerManager_Example' do
  pod 'USMusicPlayerManager', :path => '../'

  target 'USMusicPlayerManager_Tests' do
    inherit! :search_paths

    
  end
end
